env:
  es2017: true
  browser: true
  commonjs: true
  jest: true

extends: [eslint:recommended, plugin:react/recommended]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react', 'react-hooks']
rules:
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: 'warn'

settings:
  react:
    version: '16'
